; @source: RFC 5322
; @charset=UTF-32
; <https://www.rfc-editor.org/rfc/rfc5322.html>

addr-spec       =   local-part "@" domain

local-part      =   dot-atom / quoted-string

domain          =   dot-atom / domain-literal

domain-literal  =   "[" *(dtext) "]"

dtext           =   %d33-90 /          ; Printable US-ASCII
                    %d94-126 ;/         ;  characters not including
                    ;obs-dtext          ;  "[", "]", or "\"

quoted-string   =   DQUOTE *qcontent DQUOTE
qcontent        =   qtext / quoted-pair
qtext           =   %d33 / %d35-91 / %d93-126
quoted-pair     =   "\" (VCHAR / WSP)

dot-atom        =   1*atext *("." 1*atext)
atext           =   ALPHA / DIGIT / "!" / "#" / "$" / "%" / "&" / "'" / "*" / "+" / "-" / "/" /
                    "=" / "?" / "^" / "_" / "`" / "{" / "|" / "}" / "~"

domain-literal  =   "[" *dtext "]"
dtext           =   %d33-90 / %d94-126
