; <https://www.rfc-editor.org/rfc/rfc8288.html>

Link       = #link-value
link-value = "<" URI-Reference ">" *( OWS ";" OWS link-param )
link-param = token BWS [ "=" BWS ( token / quoted-string ) ]

URI-Reference = <import rfc3986-uri.abnf#rule=URI-reference>
